hwameistor/local-disk-manager

.github/workflows/period-check.yml
.github/workflows/pr.yml

```
make target for unit test
```
```release-note
```

make target for unit test

---

README-zh.md

add readme in chinese
NONE
```release-note
NONE
```

add readme in chinese

---

README.md

adjust roadmap dcscription
NONE
```release-note
NONE
```

adjust roadmap description

---

deploy/operator.yaml

Update operator image tag
NONE
```release-note
NONE
```

update operator image tag

---

images/builder/Dockerfile

builder image has some incorrect info which may cause the build failure.
```release-note
```

fixed some makefile bugs

---

deploy/operator.yaml

update imagePullPolicy
NONE
```release-note
NONE
```

update imagePullPolicy to IfNotPresent

---

test/e2e/SmokeTest/ldm.go
test/e2e/SmokeTest/utils.go

Optimize E2E test logic 
```release-note
```

Optimize E2E test logic 

---

test/e2e/SmokeTest/utils.go

Modified the name of Deployment in the E2E test 
```release-note
```

Modified the name of Deployment in the E2E test 

---

test/e2e-test.sh

Delete the account password in the shell file
```release-note
```

Delete the account password in the shell file

---

go.sum
pkg/csi/diskmanager/localdisknode_manager.go
pkg/csi/volumemanager/localdisk_volumemanager.go

1. fix ReleaseDIsk error
2. improve Nodeunpublish login
```release-note
```

fix: improce logic of Nodeunpublish and fix ReleaseDisk error

---

cmd/manager/main.go
pkg/controller/add_localdisk.go
pkg/controller/localdisk/localdisk_controller.go

fix: disk not managed error
more info see: https://github.com/hwameistor/local-disk-manager/issues/53
```release-note
```

fix: setup localdisk controller to nodemanager

---

pkg/udev/device.go

support discovery disk on ali cloud
more info see: https://github.com/hwameistor/local-disk-manager/issues/42
```release-note
```

improve: support aii cloud disk discovery

---

.github/workflows/period-check.yml
test/e2e-test.sh
test/e2e/SmokeTest/diskmanagement.go
test/e2e/SmokeTest/rawdiskvolume.go
test/e2e/SmokeTest/utils.go
test/e2e/adddisk.sh
test/e2e/deletedisk.sh
test/e2e/rollback.sh

add rawdisktest
```release-note
```

add rawdisktest

---

.github/workflows/period-check.yml
test/e2e/SmokeTest/utils.go

Increase the startup time for virtual machines
```release-note
```

Increase the startup time for virtual machines

---

pkg/builder/localdisk/localdisk.go
pkg/localdisk/localdisk.go

update disk state to fix issue: https://github.com/hwameistor/local-storage/issues/108
```release-note
NONE
```

update disk state active default

---

Makefile

Signed-off-by: jie.li <jie.li@daocloud.io>
fix: add unit-test codecov
```release-note
```

fix: add unit-test codecov

---

pkg/controller/localdiskvolume/localdiskvolume_controller.go

fix type error
```release-note
```

fix type error

---

.github/workflows/period-check.yml

Modify period-check execution time
```release-note
```

Modify period-check execution time

---

pkg/controller/localdiskclaim/localdiskclaim_controller_test.go
pkg/controller/localdiskvolume/localdiskvolume_controller_test.go

update unit test for localdiskclaim and localdiskvolume
```release-note
```

update unit test for localdiskclaim and localdiskvolume

---

.github/workflows/period-check.yml

peroid check by manual
```release-note
```

add manual peroid check

---

test/e2e-test.sh
test/e2e/SmokeTest/rawdiskvolume.go

Add logic to use the latest crd in E2E testing
```release-note
```

Add logic to use the latest crd in E2E testing

---

test/e2e-test.sh

fix e2e test
```release-note
```

fix e2e test

---

test/e2e-test.sh

Optimize image build
```release-note
```

Optimize image build

---

deploy/ioping-disk.yaml
deploy/ioping-fs.yaml

remove node selector
```release-note
NONE
```

fix ioping deploy yaml

---

pkg/builder/localdiskvolume/localdiskvolume.go
pkg/csi/diskmanager/diskmanager.go
pkg/csi/diskmanager/localdisknode_manager.go
pkg/csi/scheduler/schduler.go
pkg/csi/volumemanager/localdisk_volumemanager.go

update disk label with namespace
```release-note
```

update disk label with namespace

---

.github/workflows/period-check.yml
test/e2e/SmokeTest/diskmanagement.go
test/e2e/SmokeTest/fsvolume.go
test/e2e/SmokeTest/rawdiskvolume.go

add E2E tests
```release-note
```

add E2E tests

---

go.sum
pkg/csi/diskmanager/localdisknode_manager.go
pkg/csi/scheduler/schduler.go
pkg/csi/volumemanager/localdisk_volumemanager.go

fix scheduler error when volume is already bound
```release-note
NONE
```

fix scheduler error when volume is already bound

---

pkg/csi/diskmanager/localdisknode_manager.go
pkg/csi/scheduler/schduler.go

fix scheduler error when exist volumes
```release-note
```

fix scheduler error when exist volumes

---

pkg/controller/localdisk/localdisk_controller.go
pkg/controller/localdisk/localdisk_controller_test.go
pkg/handler/localdisk/localdisk.go

UT: add localdisk_controller unit test
```release-note
```

UT: add localdisk_controller unit test

---

test/e2e/SmokeTest/utils.go

Modify the timeout threshold of e2e test
```release-note
```

Modify the timeout threshold of e2e test

---

cmd/manager/main.go
coverage.txt
deploy/operator.yaml
pkg/csi/driver/driver.go

start CSI driver by use --csi-enable flag
```release-note
NONE
```

csi: optional start csi driver

---

README.md

update readme with CSI Volume usage
```release-note
NONE
```

docs: update CSI Volume readme

---

pkg/handler/localdisk/localdisk_test.go
pkg/handler/localdiskvolume/localdiskvolume_test.go

UT: add localdisk handler unit-test
```release-note
```

UT: add localdisk handler unit-test
